# Generated by Django 3.2 on 2021-05-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designation',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='abbr',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='abbr',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='stream',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='termyear',
            name='term',
            field=models.CharField(choices=[('1', 'Term One'), ('2', 'Term Two'), ('3', 'Term three')], max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='termyear',
            name='year',
            field=models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024')], max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='abbr',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
